// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BooksWeb.Migrations.Data;

#nullable disable

namespace BooksWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227041845_SeededCategoryData")]
    partial class SeededCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksWeb.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3351141f-420a-442a-97ca-c80b881e9f9e"),
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("82fe0a0e-4e5b-4f24-b686-c125cc85ba7e"),
                            DisplayOrder = 3,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("68e0dcef-7798-4ee2-8b78-94a77ff56ea8"),
                            DisplayOrder = 2,
                            Name = "Suspense Thriller"
                        },
                        new
                        {
                            Id = new Guid("13e0d328-d995-4293-ba1b-9a479646f77e"),
                            DisplayOrder = 5,
                            Name = "Spiritual"
                        },
                        new
                        {
                            Id = new Guid("e7f2ccb8-4ce5-4118-a458-94da45a34f02"),
                            DisplayOrder = 4,
                            Name = "Horror"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
