// <auto-generated />
using System;
using BooksWeb_Category_Razor_Pages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksWeb_Category_Razor_Pages.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksWeb_Category_Razor_Pages.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("883ce9a3-dc32-484d-8936-eeac4979f368"),
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("fe20e0e2-0664-4e47-978c-8a829672fc1f"),
                            DisplayOrder = 3,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("3d9e9ca2-1896-4545-ad23-c50be86eb8b8"),
                            DisplayOrder = 2,
                            Name = "Suspense Thriller"
                        },
                        new
                        {
                            Id = new Guid("05a26538-8bb2-4453-859c-ceff1b709aa2"),
                            DisplayOrder = 5,
                            Name = "Spiritual"
                        },
                        new
                        {
                            Id = new Guid("43dfc162-5fa0-4082-a33c-b492e9e273e1"),
                            DisplayOrder = 4,
                            Name = "Horror"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
